PROJNAME=KIPR_2
DEVICE=CY8C29466
BASEDEVICE=CY8C29000
PROJPATH=C:/Users/BRYANO~1/DOCUME~1/GitHub/KIPR-O~1/Robot2/PSOCCO~1/KIPR_2/KIPR_2/KIPR_2
PSOCDIR=C:/PROGRA~2/Cypress/PSOCDE~1/5.4/Common/CYPRES~1
INCLUDE_PATH=C:/PROGRA~2/Cypress/PSOCDE~1/5.4/Common/CYPRES~1/tools/include/CY8C29~1
CSRCS= main.c
LIBCSRCS=
STDCSRCS=
ASMSRCS=
LIBASMSRCS= enc1a_nedge.asm enc1a_nedgeint.asm enc1a_pedge.asm enc1a_pedgeint.asm enc1b_nedge.asm enc1b_nedgeint.asm enc1b_pedge.asm enc1b_pedgeint.asm ldr_adc.asm ldr_gain.asm pseudoencoder.asm pseudoencoderint.asm psocconfig.asm psocconfigtbl.asm psocgpioint.asm pwma.asm pwmaint.asm pwmb.asm pwmbint.asm servo0.asm servo0int.asm servo1.asm servo1int.asm uart.asm uartint.asm uartplus.asm ultrasonic.asm ultrasonicint.asm ultrasonicintint.asm
STDASMSRCS=
OBJECT_SOURCES= main.c
FILLVALUE=0x30
LASTROM=0x7fff
LASTRAM=0x7ff
LAST_DATARAM=0x6ff
CODECOMPRESSOR=
MORE_CFLAGS=-Wf-Osize -Wf-LMM8 -D_LMM
RELSTART=0x1a0
INC_PATH=
CDEFINES=
LIBS=
UMLIBS=
LIB_PATH=
ENABLE_ALIGN_SHIFT=0
LMM=1
SYS_INC_CONTENTS:=SYSTEM_STACK_PAGE:_equ_7 SYSTEM_STACK_BASE_ADDR:_equ_0h SYSTEM_LARGE_MEMORY_MODEL:_equ_1 SYSTEM_SMALL_MEMORY_MODEL:_equ_0 IMAGECRAFT:_equ_1 HITECH:_equ_2 TOOLCHAIN:_equ_IMAGECRAFT 
SYSTEM_TOOLS=1
CSFLOW=
CONFIG_NAMES=kipr_2 
