//*****************************************************************************
//*****************************************************************************
//  FILENAME: ENC1B_NEDGE.h
//   Version: 1.60, Updated on 2015/3/4 at 22:26:5
//  Generated by PSoC Designer 5.4.3191
//
//  DESCRIPTION:
//    ENC1B_NEDGE DigInverter User Module header file.
//-----------------------------------------------------------------------------
//      Copyright (c) Cypress Semiconductor 2015. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef ENC1B_NEDGE_INCLUDE
#define ENC1B_NEDGE_INCLUDE

#include <m8c.h>

/* Create pragmas to support proper argument and return value passing */
#pragma fastcall16  ENC1B_NEDGE_EnableInt
#pragma fastcall16  ENC1B_NEDGE_DisableInt
#pragma fastcall16  ENC1B_NEDGE_Start
#pragma fastcall16  ENC1B_NEDGE_Stop

//-------------------------------------------------
// Prototypes of the ENC1B_NEDGE API.
//-------------------------------------------------
extern void  ENC1B_NEDGE_EnableInt(void);           // Proxy Class 1
extern void  ENC1B_NEDGE_DisableInt(void);          // Proxy Class 1
extern void  ENC1B_NEDGE_Start(void);               // Proxy Class 1
extern void  ENC1B_NEDGE_Stop(void);                // Proxy Class 1

//-------------------------------------------------
// Hardware Register Definitions
//-------------------------------------------------
#pragma ioport  ENC1B_NEDGE_CONTROL_REG:    0x047
BYTE            ENC1B_NEDGE_CONTROL_REG;                   //Control register
#pragma ioport  ENC1B_NEDGE_COUNTER_REG:    0x044
BYTE            ENC1B_NEDGE_COUNTER_REG;                   //Counter register
#pragma ioport  ENC1B_NEDGE_PERIOD_REG: 0x045
BYTE            ENC1B_NEDGE_PERIOD_REG;                    //Period value register
#pragma ioport  ENC1B_NEDGE_COMPARE_REG:    0x046
BYTE            ENC1B_NEDGE_COMPARE_REG;                   //CompareValue register
#pragma ioport  ENC1B_NEDGE_FUNC_REG:   0x144
BYTE            ENC1B_NEDGE_FUNC_REG;                      //Function register
#pragma ioport  ENC1B_NEDGE_INPUT_REG:  0x145
BYTE            ENC1B_NEDGE_INPUT_REG;                     //Input register
#pragma ioport  ENC1B_NEDGE_OUTPUT_REG: 0x146
BYTE            ENC1B_NEDGE_OUTPUT_REG;                    //Output register

#endif
// end of file ENC1B_NEDGE.h
