//*****************************************************************************
//*****************************************************************************
//  FILENAME:  LDR_ADC.h
//  Version: 1.5, Updated on 2015/3/4 at 22:26:56
//  Generated by PSoC Designer 5.4.3191
//
//  DESCRIPTION:  SAR6 User Module C Language interface file.
//
//-----------------------------------------------------------------------------
//      Copyright (c) Cypress Semiconductor 2015. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef LDR_ADC_INCLUDE
#define LDR_ADC_INCLUDE

#include "m8c.h"

//-------------------------------------------------
// Defines for LDR_ADC API's.
//-------------------------------------------------
#define LDR_ADC_OFF         0
#define LDR_ADC_LOWPOWER    1
#define LDR_ADC_MEDPOWER    2
#define LDR_ADC_HIGHPOWER   3
#define LDR_ADC_FULLPOWER   3

//-------------------------------------------------
// Prototypes of the LDR_ADC API.
//-------------------------------------------------
#pragma fastcall16 LDR_ADC_Start
#pragma fastcall16 LDR_ADC_SetPower
#pragma fastcall16 LDR_ADC_cGetSample
#pragma fastcall16 LDR_ADC_Stop

extern void LDR_ADC_Start( BYTE bPowerSetting );
extern void LDR_ADC_SetPower( BYTE bPowerSetting );
extern CHAR LDR_ADC_cGetSample( void );
extern void LDR_ADC_Stop( void );

//--------------------------------------------------
// WARNING!  This function prototype will be removed
//           in a future version.
//--------------------------------------------------
#pragma fastcall16 LDR_ADC_GetSample
extern CHAR LDR_ADC_GetSample( void );

//-------------------------------------------------
// Register Addresses for LDR_ADC
//-------------------------------------------------
#pragma ioport  LDR_ADC_CR0:    0x080
BYTE            LDR_ADC_CR0;
#pragma ioport  LDR_ADC_CR1:    0x081
BYTE            LDR_ADC_CR1;
#pragma ioport  LDR_ADC_CR2:    0x082
BYTE            LDR_ADC_CR2;
#pragma ioport  LDR_ADC_CR3:    0x083
BYTE            LDR_ADC_CR3;

#endif
// end of file LDR_ADC.h
