//*****************************************************************************
//*****************************************************************************
//  FILENAME:  LightSensor.h  ( PGA )
//  Version: 3.2, Updated on 2015/3/4 at 22:26:46
//  Generated by PSoC Designer 5.4.3191
//
//  DESCRIPTION:  PGA User Module C Language interface file.
//-----------------------------------------------------------------------------
//      Copyright (c) Cypress Semiconductor 2015. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef LightSensor_INCLUDE
#define LightSensor_INCLUDE

#include <M8C.h>

//-------------------------------------------------
// Constants for LightSensor API's.
//-------------------------------------------------
#define LightSensor_OFF         0
#define LightSensor_LOWPOWER    1
#define LightSensor_MEDPOWER    2
#define LightSensor_HIGHPOWER   3

#define LightSensor_G48_0    0x0C
#define LightSensor_G24_0    0x1C

#define LightSensor_G16_0    0x08
#define LightSensor_G8_00    0x18
#define LightSensor_G5_33    0x28
#define LightSensor_G4_00    0x38
#define LightSensor_G3_20    0x48
#define LightSensor_G2_67    0x58
#define LightSensor_G2_27    0x68
#define LightSensor_G2_00    0x78
#define LightSensor_G1_78    0x88
#define LightSensor_G1_60    0x98
#define LightSensor_G1_46    0xA8
#define LightSensor_G1_33    0xB8
#define LightSensor_G1_23    0xC8
#define LightSensor_G1_14    0xD8
#define LightSensor_G1_06    0xE8
#define LightSensor_G1_00    0xF8
#define LightSensor_G0_93    0xE0
#define LightSensor_G0_87    0xD0
#define LightSensor_G0_81    0xC0
#define LightSensor_G0_75    0xB0
#define LightSensor_G0_68    0xA0
#define LightSensor_G0_62    0x90
#define LightSensor_G0_56    0x80
#define LightSensor_G0_50    0x70
#define LightSensor_G0_43    0x60
#define LightSensor_G0_37    0x50
#define LightSensor_G0_31    0x40
#define LightSensor_G0_25    0x30
#define LightSensor_G0_18    0x20
#define LightSensor_G0_12    0x10
#define LightSensor_G0_06    0x00

#define LightSensor_AGNDBUFAPI 0

#pragma fastcall16 LightSensor_Start
#pragma fastcall16 LightSensor_SetPower
#pragma fastcall16 LightSensor_SetGain
#pragma fastcall16 LightSensor_Stop

#if (LightSensor_AGNDBUFAPI)
#pragma fastcall16 LightSensor_EnableAGNDBuffer
#pragma fastcall16 LightSensor_DisableAGNDBuffer
#endif

//-------------------------------------------------
// Prototypes of the LightSensor API.
//-------------------------------------------------
extern void LightSensor_Start(BYTE bPowerSetting);     // Proxy class 2
extern void LightSensor_SetPower(BYTE bPowerSetting);  // Proxy class 2
extern void LightSensor_SetGain(BYTE bGainSetting);    // Proxy class 2
extern void LightSensor_Stop(void);                    // Proxy class 1

#if (LightSensor_AGNDBUFAPI)
extern void LightSensor_EnableAGNDBuffer(void);
extern void LightSensor_DisableAGNDBuffer(void);
#endif

//-------------------------------------------------
// Register Addresses for LightSensor
//-------------------------------------------------

#pragma ioport  LightSensor_GAIN_CR0:   0x071
BYTE            LightSensor_GAIN_CR0;
#pragma ioport  LightSensor_GAIN_CR1:   0x072
BYTE            LightSensor_GAIN_CR1;
#pragma ioport  LightSensor_GAIN_CR2:   0x073
BYTE            LightSensor_GAIN_CR2;
#pragma ioport  LightSensor_GAIN_CR3:   0x070
BYTE            LightSensor_GAIN_CR3;

#endif
// end of file LightSensor.h
