/******************************************************************************
*  Generated by PSoC Designer 5.4.2946
******************************************************************************/
// =============================================================================
// FILENAME: PSoCAPI.h
// 
// Copyright (c) Cypress Semiconductor 2013. All Rights Reserved.
// 
// NOTES:
// Do not modify this file. It is generated by PSoC Designer each time the
// generate application function is run. The values of the parameters in this
// file can be modified by changing the values of the global parameters in the
// device editor.
// 
// =============================================================================
 
#ifndef __PSOCAPI_H
#define __PSOCAPI_H

#include "PSoCGPIOINT.h"
#include "DelSig_1.h"
#include "ENC1A_NEDGE.h"
#include "ENC1A_PEDGE.h"
#include "ENC1B_NEDGE.h"
#include "ENC1B_PEDGE.h"
#include "LightSensor.h"
#include "PWMA.h"
#include "PWMB.h"
#include "Servo0.h"
#include "Servo1.h"
#include "UART.h"
#include "VelTimer.h"

#endif
