//*****************************************************************************
//*****************************************************************************
//  FILENAME:  Reflect1_Gain.h  ( PGA )
//  Version: 3.2, Updated on 2015/3/4 at 22:26:46
//  Generated by PSoC Designer 5.4.3191
//
//  DESCRIPTION:  PGA User Module C Language interface file.
//-----------------------------------------------------------------------------
//      Copyright (c) Cypress Semiconductor 2015. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef Reflect1_Gain_INCLUDE
#define Reflect1_Gain_INCLUDE

#include <M8C.h>

//-------------------------------------------------
// Constants for Reflect1_Gain API's.
//-------------------------------------------------
#define Reflect1_Gain_OFF         0
#define Reflect1_Gain_LOWPOWER    1
#define Reflect1_Gain_MEDPOWER    2
#define Reflect1_Gain_HIGHPOWER   3

#define Reflect1_Gain_G48_0    0x0C
#define Reflect1_Gain_G24_0    0x1C

#define Reflect1_Gain_G16_0    0x08
#define Reflect1_Gain_G8_00    0x18
#define Reflect1_Gain_G5_33    0x28
#define Reflect1_Gain_G4_00    0x38
#define Reflect1_Gain_G3_20    0x48
#define Reflect1_Gain_G2_67    0x58
#define Reflect1_Gain_G2_27    0x68
#define Reflect1_Gain_G2_00    0x78
#define Reflect1_Gain_G1_78    0x88
#define Reflect1_Gain_G1_60    0x98
#define Reflect1_Gain_G1_46    0xA8
#define Reflect1_Gain_G1_33    0xB8
#define Reflect1_Gain_G1_23    0xC8
#define Reflect1_Gain_G1_14    0xD8
#define Reflect1_Gain_G1_06    0xE8
#define Reflect1_Gain_G1_00    0xF8
#define Reflect1_Gain_G0_93    0xE0
#define Reflect1_Gain_G0_87    0xD0
#define Reflect1_Gain_G0_81    0xC0
#define Reflect1_Gain_G0_75    0xB0
#define Reflect1_Gain_G0_68    0xA0
#define Reflect1_Gain_G0_62    0x90
#define Reflect1_Gain_G0_56    0x80
#define Reflect1_Gain_G0_50    0x70
#define Reflect1_Gain_G0_43    0x60
#define Reflect1_Gain_G0_37    0x50
#define Reflect1_Gain_G0_31    0x40
#define Reflect1_Gain_G0_25    0x30
#define Reflect1_Gain_G0_18    0x20
#define Reflect1_Gain_G0_12    0x10
#define Reflect1_Gain_G0_06    0x00

#define Reflect1_Gain_AGNDBUFAPI 0

#pragma fastcall16 Reflect1_Gain_Start
#pragma fastcall16 Reflect1_Gain_SetPower
#pragma fastcall16 Reflect1_Gain_SetGain
#pragma fastcall16 Reflect1_Gain_Stop

#if (Reflect1_Gain_AGNDBUFAPI)
#pragma fastcall16 Reflect1_Gain_EnableAGNDBuffer
#pragma fastcall16 Reflect1_Gain_DisableAGNDBuffer
#endif

//-------------------------------------------------
// Prototypes of the Reflect1_Gain API.
//-------------------------------------------------
extern void Reflect1_Gain_Start(BYTE bPowerSetting);     // Proxy class 2
extern void Reflect1_Gain_SetPower(BYTE bPowerSetting);  // Proxy class 2
extern void Reflect1_Gain_SetGain(BYTE bGainSetting);    // Proxy class 2
extern void Reflect1_Gain_Stop(void);                    // Proxy class 1

#if (Reflect1_Gain_AGNDBUFAPI)
extern void Reflect1_Gain_EnableAGNDBuffer(void);
extern void Reflect1_Gain_DisableAGNDBuffer(void);
#endif

//-------------------------------------------------
// Register Addresses for Reflect1_Gain
//-------------------------------------------------

#pragma ioport  Reflect1_Gain_GAIN_CR0: 0x079
BYTE            Reflect1_Gain_GAIN_CR0;
#pragma ioport  Reflect1_Gain_GAIN_CR1: 0x07a
BYTE            Reflect1_Gain_GAIN_CR1;
#pragma ioport  Reflect1_Gain_GAIN_CR2: 0x07b
BYTE            Reflect1_Gain_GAIN_CR2;
#pragma ioport  Reflect1_Gain_GAIN_CR3: 0x078
BYTE            Reflect1_Gain_GAIN_CR3;

#endif
// end of file Reflect1_Gain.h
