//*****************************************************************************
//*****************************************************************************
//  FILENAME:  Reflect0_ADC.h
//  Version: 1.5, Updated on 2015/3/4 at 22:26:56
//  Generated by PSoC Designer 5.4.3191
//
//  DESCRIPTION:  SAR6 User Module C Language interface file.
//
//-----------------------------------------------------------------------------
//      Copyright (c) Cypress Semiconductor 2015. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef Reflect0_ADC_INCLUDE
#define Reflect0_ADC_INCLUDE

#include "m8c.h"

//-------------------------------------------------
// Defines for Reflect0_ADC API's.
//-------------------------------------------------
#define Reflect0_ADC_OFF         0
#define Reflect0_ADC_LOWPOWER    1
#define Reflect0_ADC_MEDPOWER    2
#define Reflect0_ADC_HIGHPOWER   3
#define Reflect0_ADC_FULLPOWER   3

//-------------------------------------------------
// Prototypes of the Reflect0_ADC API.
//-------------------------------------------------
#pragma fastcall16 Reflect0_ADC_Start
#pragma fastcall16 Reflect0_ADC_SetPower
#pragma fastcall16 Reflect0_ADC_cGetSample
#pragma fastcall16 Reflect0_ADC_Stop

extern void Reflect0_ADC_Start( BYTE bPowerSetting );
extern void Reflect0_ADC_SetPower( BYTE bPowerSetting );
extern CHAR Reflect0_ADC_cGetSample( void );
extern void Reflect0_ADC_Stop( void );

//--------------------------------------------------
// WARNING!  This function prototype will be removed
//           in a future version.
//--------------------------------------------------
#pragma fastcall16 Reflect0_ADC_GetSample
extern CHAR Reflect0_ADC_GetSample( void );

//-------------------------------------------------
// Register Addresses for Reflect0_ADC
//-------------------------------------------------
#pragma ioport  Reflect0_ADC_CR0:   0x084
BYTE            Reflect0_ADC_CR0;
#pragma ioport  Reflect0_ADC_CR1:   0x085
BYTE            Reflect0_ADC_CR1;
#pragma ioport  Reflect0_ADC_CR2:   0x086
BYTE            Reflect0_ADC_CR2;
#pragma ioport  Reflect0_ADC_CR3:   0x087
BYTE            Reflect0_ADC_CR3;

#endif
// end of file Reflect0_ADC.h
