//*****************************************************************************
//*****************************************************************************
//  FILENAME:  Reflect1_ADC.h
//  Version: 1.5, Updated on 2015/3/4 at 22:26:56
//  Generated by PSoC Designer 5.4.3191
//
//  DESCRIPTION:  SAR6 User Module C Language interface file.
//
//-----------------------------------------------------------------------------
//      Copyright (c) Cypress Semiconductor 2015. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef Reflect1_ADC_INCLUDE
#define Reflect1_ADC_INCLUDE

#include "m8c.h"

//-------------------------------------------------
// Defines for Reflect1_ADC API's.
//-------------------------------------------------
#define Reflect1_ADC_OFF         0
#define Reflect1_ADC_LOWPOWER    1
#define Reflect1_ADC_MEDPOWER    2
#define Reflect1_ADC_HIGHPOWER   3
#define Reflect1_ADC_FULLPOWER   3

//-------------------------------------------------
// Prototypes of the Reflect1_ADC API.
//-------------------------------------------------
#pragma fastcall16 Reflect1_ADC_Start
#pragma fastcall16 Reflect1_ADC_SetPower
#pragma fastcall16 Reflect1_ADC_cGetSample
#pragma fastcall16 Reflect1_ADC_Stop

extern void Reflect1_ADC_Start( BYTE bPowerSetting );
extern void Reflect1_ADC_SetPower( BYTE bPowerSetting );
extern CHAR Reflect1_ADC_cGetSample( void );
extern void Reflect1_ADC_Stop( void );

//--------------------------------------------------
// WARNING!  This function prototype will be removed
//           in a future version.
//--------------------------------------------------
#pragma fastcall16 Reflect1_ADC_GetSample
extern CHAR Reflect1_ADC_GetSample( void );

//-------------------------------------------------
// Register Addresses for Reflect1_ADC
//-------------------------------------------------
#pragma ioport  Reflect1_ADC_CR0:   0x088
BYTE            Reflect1_ADC_CR0;
#pragma ioport  Reflect1_ADC_CR1:   0x089
BYTE            Reflect1_ADC_CR1;
#pragma ioport  Reflect1_ADC_CR2:   0x08a
BYTE            Reflect1_ADC_CR2;
#pragma ioport  Reflect1_ADC_CR3:   0x08b
BYTE            Reflect1_ADC_CR3;

#endif
// end of file Reflect1_ADC.h
