//*****************************************************************************
//*****************************************************************************
//  FILENAME: ENC1B.h
//  Version: 1.3, Updated on 2014/7/14 at 8:13:28
//  Generated by PSoC Designer 5.4.2946
//
//  DESCRIPTION: DigitalBuffers User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2014. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef ENC1B_INCLUDE
#define ENC1B_INCLUDE

#include <m8c.h>

#pragma fastcall16 ENC1B_EnableInt
#pragma fastcall16 ENC1B_DisableInt
#pragma fastcall16 ENC1B_Start
#pragma fastcall16 ENC1B_Stop

//-------------------------------------------------
// Prototypes of the ENC1B API.
//-------------------------------------------------

extern void ENC1B_EnableInt(void);
extern void ENC1B_DisableInt(void);
extern void ENC1B_Start(void);
extern void ENC1B_Stop(void);


//--------------------------------------------------
// Constants for ENC1B API's.
//--------------------------------------------------
#define ENC1B_CONTROL_REG_START_BIT            ( 0x01 )
#define ENC1B_INT_REG_ADDR                     ( 0x0e1 )
#define ENC1B_INT_MASK                         ( 0x20 )


//--------------------------------------------------
// Constants for ENC1B user defined values
//--------------------------------------------------
#pragma ioport  ENC1B_DATA_0_REG:   0x034                  //DR0 Count register
BYTE            ENC1B_DATA_0_REG;
#pragma ioport  ENC1B_DATA_1_REG:   0x035                  //DR1 Period register
BYTE            ENC1B_DATA_1_REG;
#pragma ioport  ENC1B_DATA_2_REG:   0x036                  //DR2 Compare register
BYTE            ENC1B_DATA_2_REG;
#pragma ioport  ENC1B_CONTROL_REG:  0x037                  //Control register
BYTE            ENC1B_CONTROL_REG;
#pragma ioport  ENC1B_FUNC_REG: 0x134                      //Function register
BYTE            ENC1B_FUNC_REG;
#pragma ioport  ENC1B_INPUT_REG:    0x135                  //Input register
BYTE            ENC1B_INPUT_REG;
#pragma ioport  ENC1B_OUTPUT_REG:   0x136                  //Output register
BYTE            ENC1B_OUTPUT_REG;
#pragma ioport  ENC1B_INT_REG:       0x0e1                 //Interrupt Mask Register
BYTE            ENC1B_INT_REG;


//-------------------------------------------------
// Register Addresses for ENC1B
//-------------------------------------------------


//-------------------------------------------------
// ENC1B Macro 'Functions'
//-------------------------------------------------

#define ENC1B_Start_M \
   ENC1B_CONTROL_REG |=  ENC1B_CONTROL_REG_START_BIT

#define ENC1B_Stop_M  \
   ENC1B_CONTROL_REG &= ~ENC1B_CONTROL_REG_START_BIT

#define ENC1B_EnableInt_M   \
   M8C_EnableIntMask(ENC1B_INT_REG, ENC1B_INT_MASK)

#define ENC1B_DisableInt_M  \
   M8C_DisableIntMask(ENC1B_INT_REG, ENC1B_INT_MASK)

#endif
// end of file ENC1B.h
